sonar.projectKey=tasklist-backend-fabre
sonar.projectName=Tasklist Frontend Fabre
sonar.sources=src
sonar.exclusions=src/__tests__/**,src/main.tsx
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.tsx,src/__tests__/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.token=sqp_940869aa0fe0c9f4b125d896f0413507888858f8
